spring:
  data:
    mongodb:
      uri: mongodb+srv://${USER_DB:admin}:${PASSWORD_DB}@webfluxcluster.oe40lxl.mongodb.net/${DB_NAME:webflux-course}?retryWrites=true&w=majority
      auto-index-creation: true
  application:
    name: webflux


server:
  port: 8082